#!/bin/sh

#
# Copyright © 2015-2021 the original authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running:
#
#   (1) You need a POSIX-compliant shell to run this script. If your /bin/sh does
#       not find it, but you have some other compatible shell available, you may
#       want to edit this line so it runs the shell you do have.
#
#   (2) The APK built with Gradle is unsigned and unoptimized. You will
#       need to sign your APK before it can be installed on real devices.
#
##############################################################################

# Attempt to set APP_HOME
# Resolve links: $0 may be a symlink
app_path=$0

# Need this for daisy-chained symlinks.
while
    APP_HOME=${app_path%"${app_path##*/}"}
    [ -h "$app_path" ]
do
    ls=$( ls -ld "$app_path" )
    link=${ls#*' -> '}
    case $link in
    /*)
        app_path=$link
        ;;
    *)
        app_path=$APP_HOME$link
        ;;
    esac
done

APP_HOME=$( cd "${APP_HOME:-./}" && pwd -P ) || exit

APP_NAME="Gradle"
APP_JAR=$(find "$APP_HOME" -type f -name "gradle-wrapper.jar" 2>/dev/null | head -n 1)

if [ -z "$APP_JAR" ]; then
    echo "Error: gradle-wrapper.jar not found"
    exit 1
fi

exec java -cp "$APP_JAR" org.gradle.wrapper.GradleWrapperMain "$@"
